### PR TITLE
deployment test

### PR DESCRIPTION
**Pull request by hanyhesham**

### CODE REVIEW

**Comment by hanyhesham** [comment]
@GINAGC 

**Changes added after local and AKS deployments:**

  1- Add storage class to values file to fix PVC binding issue in AKS deployment:
   
    Error:  default-scheduler  0/3 nodes are available: 3 node(s) had volume node affinity conflict.

  2- Add transactionstoresecret before deployment.
 
  3- Edit secretKeyRef name to remove caps.

  4- Replace icapmanagementui image tag with a valid value.
  
  5- Update readme with the instructions.

**Comment by mahnouman** [comment]
Hello @hanyhesham , what is this PR about? i.e. what is the relevant issue(s)? Thanks

**Comment by hanyhesham** [comment]
Hello @mahnouman 

This is related to that issue:

https://github.com/k8-proxy/gp-github/issues/1

**Comment by mahnouman** [comment]
Thanks @hanyhesham ,,, hello @pranaysahith please review and adjust if the info should be in the other readme files. Thanks

**Comment by mahnouman** [comment]
Hi @azopat please check if we need something from this PR

**Comment by azopat** [comment]
hi @mahnouman  no it's deprecated now

**Pull request closed without merging**
